name: football_prediction
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - beautifulsoup4
  - scikit-learn
  - ruff
  - pytest
  - pytest-mock
  - requests
  - tqdm
  - lxml
  - jupyter
  - html5lib
